// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "community" section.

import React from 'react';
import TestimonialMarqueeCards from '@/components/sections/testimonial/TestimonialMarqueeCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function CommunitySection(): React.JSX.Element {
  return (
    <div id="community" data-section="community">
        <SectionErrorBoundary name="community">
              <TestimonialMarqueeCards
          tag="Community"
          title="The Study Society"
          description="Join our growing member community."
          testimonials={[
            {
              name: "Sarah Chen",          role: "PhD Candidate",          quote: "Finally, a place that takes study seriously.",          imageSrc: "http://img.b2bpic.net/free-photo/close-up-cup-coffee_23-2148494608.jpg"},
            {
              name: "David Miller",          role: "Entrepreneur",          quote: "The perfect remote work environment.",          imageSrc: "http://img.b2bpic.net/free-photo/wifi-signal-icon-blue-color_187299-46876.jpg"},
            {
              name: "Elena Ross",          role: "Freelancer",          quote: "Love the networking events here.",          imageSrc: "http://img.b2bpic.net/free-photo/room-domestic-lifestyle-couch-residential_1203-4120.jpg"},
            {
              name: "James Smith",          role: "Faculty",          quote: "Elegant and professional atmosphere.",          imageSrc: "http://img.b2bpic.net/free-photo/young-male-barista-preparing-coffee-coffee-shop_1303-31776.jpg"},
            {
              name: "Maria Lopez",          role: "Creative",          quote: "My favorite creative hub.",          imageSrc: "http://img.b2bpic.net/free-photo/blank-screen-laptop-desk_53876-42866.jpg"},
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
