// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTwoColumn from '@/components/sections/faq/FaqTwoColumn';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqTwoColumn
          tag="FAQ"
          title="Common Questions"
          description="Everything you need to know about our upcoming location."
          items={[
            {
              question: "Where are you located?",          answer: "Currently securing our flagship location near a major Long Island university."},
            {
              question: "When do you open?",          answer: "We are proud to announce our opening in Spring 2027."},
            {
              question: "Do you offer membership?",          answer: "Yes, The Study Society program will launch with our opening."},
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
