// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features" section.

import React from 'react';
import FeaturesBento from '@/components/sections/features/FeaturesBento';
import { Battery, Book, Coffee, Leaf, MessageSquare, User, Wifi, Zap } from "lucide-react";
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FeaturesSection(): React.JSX.Element {
  return (
    <div id="features" data-section="features">
        <SectionErrorBoundary name="features">
              <FeaturesBento
          tag="Experience"
          title="Why Choose The Study Café"
          description="Sophisticated spaces crafted for productivity."
          features={[
            {
              title: "Specialty Coffee",          description: "Handcrafted perfection.",          bentoComponent: "info-card-marquee",          infoCards: [
                {
                  icon: Coffee,
                  label: "Espresso",              value: "Premium"},
                {
                  icon: Zap,
                  label: "Cold Brew",              value: "Bold"},
                {
                  icon: Leaf,
                  label: "Matcha",              value: "Organic"},
              ],
            },
            {
              title: "Study Spaces",          description: "Quiet rooms and private pods.",          bentoComponent: "tilted-stack-cards",          stackCards: [
                {
                  icon: Book,
                  title: "Rooms",              subtitle: "Study",              detail: "Private rooms"},
                {
                  icon: Wifi,
                  title: "Internet",              subtitle: "High Speed",              detail: "Ultra fast"},
                {
                  icon: Battery,
                  title: "Power",              subtitle: "Outlets",              detail: "Everywhere"},
              ],
            },
            {
              title: "Community",          description: "Where ideas meet.",          bentoComponent: "chat-marquee",          aiIcon: MessageSquare,
              userIcon: User,
              exchanges: [
                {
                  userMessage: "Study night event?",              aiResponse: "Weekly gatherings!"},
                {
                  userMessage: "Networking?",              aiResponse: "Monthly mixers!"},
              ],
              placeholder: "Events..."},
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
