// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroBrand from '@/components/sections/hero/HeroBrand';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroBrand
          brand="More Than Coffee."
          description="A place to study, create, and connect. Coming Spring 2027."
          primaryButton={{
            text: "Join the Waitlist",        href: "#waitlist"}}
          secondaryButton={{
            text: "Explore Our Vision",        href: "#about"}}
          imageSrc="http://img.b2bpic.net/free-photo/elegant-cozy-office-with-laptop_23-2149636249.jpg"
        />
        </SectionErrorBoundary>
      </div>
  );
}
