// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "lounge" section.

import React from 'react';
import MetricsMediaCards from '@/components/sections/metrics/MetricsMediaCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function LoungeSection(): React.JSX.Element {
  return (
    <div id="lounge" data-section="lounge">
        <SectionErrorBoundary name="lounge">
              <MetricsMediaCards
          tag="Lounge"
          title="Study Focused Environment"
          description="Productivity-first design."
          metrics={[
            {
              value: "10+",          title: "Study Rooms",          description: "Soundproof",          imageSrc: "http://img.b2bpic.net/free-photo/arrangement-with-books-dark-background_23-2148898276.jpg"},
            {
              value: "100%",          title: "Outlet Coverage",          description: "Work anywhere",          imageSrc: "http://img.b2bpic.net/free-photo/still-life-office-desk-mess_23-2150164786.jpg"},
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
