// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "waitlist" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function WaitlistSection(): React.JSX.Element {
  return (
    <div id="waitlist" data-section="waitlist">
        <SectionErrorBoundary name="waitlist">
              <ContactCta
          tag="Waitlist"
          text="Be First in Line for Fall 2027."
          primaryButton={{
            text: "Join the Waitlist",        href: "#"}}
          secondaryButton={{
            text: "Follow on IG",        href: "#"}}
        />
        </SectionErrorBoundary>
      </div>
  );
}
